version: 0.2
phases:
  build:
    commands:
      - echo Command - `date` Starting the build
  post_build:
    commands:
      - mkdir lf_1
      - cp -R lambda/lf1 lf_1/
      - cd lf_1/
      - zip -qr lf_1.zip ./*
      - mv lf_1.zip ../
      - cd ../
      - mkdir lf_2
      - cp -R lambda/lf2 lf_2/
      - cd lf_2/
      - zip -qr lf_2.zip ./*
      - mv lf_2.zip ../
      - cd ../
      - mkdir ui
      - cp -rv apiGateway-js-sdk ui/
      - cp -rv lib ui/
      - cp apigClient.js ui/
      - cp google_style.css ui/
      - cp index.html ui/
      - cp style1.css ui/
      - cp script.js ui/
      - cp render.js ui/
      - cd ui/
      - zip -qr ui.zip ./*
      - mv ui.zip ../
      - cd ../
      - echo Command - `date` Build Complete
      - aws s3 cp ui s3://nm3223.ui.b1.w6998.ccbd.f2021/ --recursive
      - aws s3 cp ./lf_1.zip s3://nm3223.build-archive/current_build/lf_1.zip
      - aws s3 cp ./lf_2.zip s3://nm3223.build-archive/current_build/lf_2.zip
      - aws s3 cp ./ui.zip s3://nm3223.build-archive/current_build/ui.zip
      - aws cloudformation package --template-file formation_template.yml --s3-bucket nm3223.build-archive --output-template-file output_formation_template.yml
artifacts:
  type: zip
  files:
    - output_formation_template.yml
    - formation_template.yml