version: 0.1
phases:
  install:
    commands:
      - echo "Starting the build .."
      - aws cloudformation package --template-file formation-spec.yml --s3-bucket nm3223.build-archive --output-template-file output-template.yml
      - aws cloudformation package --template-file ui-spec.yml --s3-bucket nm3223.ui.b1.w6998.ccbd.f2021 --output-template-file ui-output-template.yml
      - echo "Artifact Build Complete .."
      - cd ui
      - zip -r ui.zip .
artificats:
  type: zip
  files:
    - output-template.yml
    - ui-output-template.yml
    - ui.zip