version: 0.1
phases:
  install:
    commands:
      - echo "Starting the build .."
      - aws cloudformation package --template-file formation-spec.json --s3-bucket nm3223.build-archive --output-template-file output-template.yml
      - echo "Artifact Build Complete .."
artificats:
  files:
    - output-template.yml