version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file formation-template.yml --s3-bucket codepipeline-us-east-1-482061862160 --output-template-file output-template.yml
artificats:
  type: zip
  files:
    - formation-template.yml
    - outputTemplate.yml