AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  LF1Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: nm3223-hw2-lambdafunction1-indexphotos.lambda_handler
      Runtime: python3.7
      CodeUri: ./lambdas/
  LF2Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: nm3223-hw2-lambdafunction2-searchphotos.lambda_handler
      Runtime: python3.7
      CodeUri: ./lambdas/