AWSTemplateFormatVersion: "2010-09-09"
Description: Formation Template
Resources:
  LambdaIndexResource: #An inline comment
    Type: "AWS::Lambda::Function"
    Properties: 
      Code:
        S3Bucket: codebucket-1729
        S3Key: code-main-branch.zip
      Description: Formation
      Tags:
        -
          Value: SAM
          Key: lambda:createdBy
      MemorySize: 128
      REGION: us-east-1
      Handler: lambda_function.lambda_handler
      Role: nm3223-hw2-lambdafunction1-indexphotos-role-6nnzqkrg
      TimeOut: 30,
      RunTime: "python3.6"
      FunctionName: nm3223-hw2-lambdafunction1-indexphotos
  LambdaSearchResource: #An inline comment
    Type: "AWS::Lambda::Function"
    Properties: 
      Code:
        S3Bucket: codebucket-1729
        S3Key: code-main-branch.zip
      Description: Formation
      Tags:
        -
          Value: SAM
          Key: lambda:createdBy
      MemorySize: 128
      REGION: us-east-1
      Handler: lambda_function.lambda_handler
      Role: nm3223-hw2-lambdafunction2-searchphotos-role-6tmhd8m3
      TimeOut: 30,
      RunTime: "python3.6"
      FunctionName: nm3223-hw2-lambdafunction2-searchphotos

