AWSTemplateFormatVersion: "2010-09-09"
Description: >
  This is the formation template
  for Lambda / UI and Elastic
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  LF1Function:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
        - x86_64
      CodeUri: ./lambda/lf1
      Description: Index Photos Lambda [CP]
      FunctionName: nm3223-hw2-lambdafunction1-cp-indexphotos
      Handler: lambda_handler
      Role: arn:aws:iam::858031629516:role/service-role/nm3223-hw2-lambdafunction1-indexphotos-role-6nnzqkrg
      Runtime: python3.7
  LF2Function:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
        - x86_64
      CodeUri: ./lambda/lf2
      Description: Search Photos Lambda [CP]
      FunctionName: nm3223-hw2-lambdafunction2-cp-searchphotos
      Handler: lambda_handler
      Role: arn:aws:iam::858031629516:role/service-role/nm3223-hw2-lambdafunction2-searchphotos-role-6tmhd8m3
      Runtime: python3.7
  ESInstance:
    Type: AWS::Elasticsearch::Domain
    Properties:
      DomainName: cp-index-photos
      ElasticsearchClusterConfig:
        InstanceType: m3.medium.elasticsearch
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: cp-index-photos
  PhotoGateway":
      Type: AWS::ApiGateway::Deployment
      Properties:
        RestApiId:
          Ref: ServerlessRestApi
        Description: RestApi deployment
        StageName: Stage
  ServerlessRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Body:
          info:
            version: 1.0
            title:
              Ref: AWS::StackName
          paths:
            /search-photos:
              get:
                x-amazon-apigateway-integration:
                  httpMethod: POST
                  type: aws_proxy
                  uri:
                    Fn::Sub: arn:aws:iam::858031629516:role/service-role/nm3223-hw2-lambdafunction1-indexphotos-role-6nnzqkrg
                responses:
          swagger: 2.0